_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  # WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  WEIGHTS: "/content/drive/My Drive/Colab Notebooks/transfiner-opt/sythntic_pod_pretrain-14*14 ROIpool/model_final.pth"
  MASK_ON: True
  RESNETS:
    DEPTH: 101
SOLVER:
  STEPS: (210000, 250000)
  MAX_ITER: 270000
TEST:
  EVAL_PERIOD: 10000 
OUTPUT_DIR: "./multi_pod_output_101_3x_14_14_seg_pre_train_cls_14_14"
